### ISSUE TITLE
JAVA_HOME not set on apple m1

### ISSUE THREAD

**Issue by EeeMt** [jenv/jenv#339]
jenv 0.5.4

I execute follow steps on my m1 MBA and intel MBP:
```shell
1. brew install jenv
2. echo eval "$(jenv init -)" >> /Users/xiquan/.zshrc
3. jenv add $(/usr/libexec/java_home)
4. jenv global 1.8
5. <open new terminal tab>
6. echo ${JAVA_HOME}
```
The intel MBP works fine while the m1 MBA not.

Environment info of the m1 MBA:
```shell
Last login: Wed Oct 20 22:42:00 on ttys008
➜  ~ jenv --version
jenv 0.5.4
➜  ~ jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
➜  ~ echo $PATH
/Users/xiquan/.jenv/shims:/Users/xiquan/.jenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/opt/fzf/bin
➜  ~ grep -v '#' .zshrc | grep -ve '^$'
export ZSH="/Users/xiquan/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
export PATH="$HOME/.jenv/bin:$PATH"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval export PATH="/Users/xiquan/.jenv/shims:${PATH}"
export JENV_SHELL=zsh
export JENV_LOADED=1
unset JAVA_HOME
source '/opt/homebrew/Cellar/jenv/0.5.4/libexec/libexec/../completions/jenv.zsh'
jenv rehash 2>/dev/null
jenv refresh-plugins
jenv() {
  typeset command
  command="$1"
    shift
  fi
  case "$command" in
  enable-plugin|rehash|shell|shell-options)
    eval `jenv "sh-$command" "$@"`;;
  *)
    command jenv "$command" "$@";;
  esac
}
➜  ~ echo $JAVA_HOME

➜  ~ ls .jenv/plugins
export gradle maven
➜  ~ jenv enable-plugin export
export plugin already enabled
➜  ~ jenv version
11 (set by /Users/xiquan/.java-version)
➜  ~ jenv versions
  system
  1.8
  1.8.0.302
* 11 (set by /Users/xiquan/.java-version)
  11.0
  11.0.12
  17
  openjdk64-11.0.12
  zulu64-1.8.0.302
  zulu64-17
➜  ~ command -v java
/Users/xiquan/.jenv/shims/java
➜  ~
```

**Comment by kito99** [comment]
I was able to get this working by doing the following:

```
rm ~/Library/LaunchAgents/jenv-environment.plist
jenv macos-javahome
```

To view the file:

```
cat ~/Library/LaunchAgents/jenv-environment.plist
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
   <key>Label</key>
   <string>my.startup</string>
   <key>ProgramArguments</key>
   <array>
     <string>sh</string>
     <string>-c</string>
     <string>
     launchctl setenv JAVA_HOME /usr/local/opt/jenv/versions/11.0 ;
     </string>
   </array>
   <key>RunAtLoad</key>
   <true/>
 </dict>
 </plist>
```

Verify in a new shell:

```
interneuron:~ kito$ echo $JAVA_HOME
/usr/local/opt/jenv/versions/11.0
```

**Comment by jmayday** [comment]
Exactly same issue on my MacBook Pro M1.

**Comment by dusiema** [comment]
Same problem here on a M1 Mac. 

Using Kotlin Multiplatform Build which is runs from xCode with a `run script`. 
I ended up manually editing `~/Library/LaunchAgents/jenv-environment.plist` and set the right `JAVA_HOME` to get going.

**Comment by tudorvirga** [comment]
Got the same problem and I got it fixed by running: `jenv rehash` followed by a `exec $SHELL -l`. Hope it helps someone.

**Comment by jebeaudet** [comment]
For me, I fixed it just by running `jenv enable-plugin export` and by restarting my shell. Hopefully it helps someone
Source: https://github.com/albert-hg/Mac-M1-First-Setting-Guide/blob/main/README.md#jenv

**Comment by kpitt** [comment]
I was having the same problem here, but not with a GUI application so I knew `~/LibraryLaunchAgents/jenv-environment.plist` wasn't the problem. For me, `jenv` wasn't setting JAVA_HOME in the shell, either on startup or when changing to a directory containing a local `.java-version` file. I checked that `jenv` was being initialized in my startup scripts, that the `export` plugin was enabled, and that `jenv javahome` was reporting the correct directory, but I still had no `JAVA_*` or `JDK_*` environment variables.

After banging my head against the wall for way too long, I finally figured out that the init-caching I use in my shell configuration had cached the `jenv init -` statements _before_ I enabled the `export` plugin. Even though `jenv` itself was getting initialized, the line that should have source'd the export hook function was missing. After updating the cached init to include the proper `export` plugin initialization, everything now works as expected.

**Comment by glesirok** [comment]
MacBook Air M1.

you also need to exec:
`echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc`
The PATH env variable is what you missed.  
Source:https://www.jenv.be/

Then enable the export plugin
`jenv enable-plugin export
exec $SHELL -l`

I found that if PATH is not set correctly, jenv wouldn't set JAVA_HOME even if the plugin is enabled

**Comment by liuyujie-tx** [comment]
> For me, I fixed it just by running `jenv enable-plugin export` and by restarting my shell. Hopefully it helps someone Source: https://github.com/albert-hg/Mac-M1-First-Setting-Guide/blob/main/README.md#jenv

Thanks！ That's helpful
